name: pretty_qr_code
description: A highly customizable Flutter widget that makes it easy to render QR codes.

version: 3.5.0
homepage: https://github.com/promops/flutter_pretty_qr

topics:
  - qr
  - pretty-qr
  - pretty-widgets

screenshots:
  - description: A smoothed QR code.
    path: resources/qr-code-blue.png

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  # tests
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^2.0.1
  dart_code_metrics_presets: ^2.24.0
