name: pretty_qr_code
description: Pretty QR code for Flutter. You can round the edges with parameter or use the standard view.

version: 3.2.1
homepage: https://github.com/promops/flutter_pretty_qr

topics:
  - qr
  - pretty-qr
  - pretty-widgets

screenshots:
  - description: A smoothed QR code.
    path: resources/qr-code-blue.png

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  # tests
  test: ^1.24.9
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^2.0.1
  dart_code_metrics_presets: ^2.9.0
