name: pretty_qr_code
description: Pretty QR code for Flutter. You can round the edges with parameter or use the standard view.
version: 3.0.0
homepage: https://github.com/promops/flutter_pretty_qr

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

